import type { Metadata } from "next";
import { Indie_Flower } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import "./globals.css";

const indieFlower = Indie_Flower({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WIWEK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={indieFlower.className}>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
